### ISSUE TITLE
Full Stack Discussion

### ISSUE THREAD

**Issue by jmartin84** [cohesivelabs/glue#2]

**Comment by CWSpear** [comment]
I'm still in favor of Angular, Angular 2 if possible. I also like LoopBack (or similar) for the 3-way syncing. I like that over, say, Firebase, as it is much more customizable and self-hosted. Firebase specifically... I want to like it, but the first times I've tried it... I really don't.

**Comment by jmartin84** [comment]
Loopback is the isomorphic one right? 

If we did Angular 2, what problems would we run into? I haven't really been following its stability.

**Comment by CWSpear** [comment]
Angular 2 is currently in Developer Preview. I don't know what that means. I think the core is decent, and I see people doing stuff with it. But a lot of the critical components to really make a legitimate app aren't there. Glue has a pretty narrow view, so it may be plausible.

**Comment by jmartin84** [comment]
Yeah I agree that the scope may be limited enough that we could get away with a developer preview. 

Isomorphic is my favorite buzzword right now so I do like the idea of using loopback

**Comment by CWSpear** [comment]
Yes, LoopBack is isomorphic... the kind that actually matters, imo. Rendering on the server is hardly cool! You can write methods in Node and call them "directly" from the browser, all done pretty automatically.

**Comment by jmartin84** [comment]
Yeah that sounds fancy and fun

**Comment by jmartin84** [comment]
babel!
flow?

**Comment by CWSpear** [comment]
Sure, I guess. I think we should use Babel on the backend, too... does Babel allow you to target specific targets so it'd leave es6 stuff that is supported alone?

**Comment by CWSpear** [comment]
Worth noting, if we use Angular 2, we'd be using the regular version, labelled "Isomorphic LoopBack" on http://loopback.io/examples/ and do _not_ need (and _should_ not use) the Angular flavor.

**Comment by jmartin84** [comment]
Good question, I would be surprised if it didn't do some sort of native feature check - but something to find out.

I would want to do babel end to end, I don't think having two different javascript subsets in the same project to be the best idea.

Database(s)?

Mongo - document store would be pretty nice for text snippets
PG - multiparadigm does give us a lot of flexibility
Redis - do we actually need much more than a key value store?

**Comment by CWSpear** [comment]
I think Postgres. It's given me the least amount of heartburn lately. We also do have a _little_ bit of relational so users can look at past items, etc, if we want to go that direction.

**Comment by jmartin84** [comment]
I think an initial version it would be fine to not track any of that stuff, but I don't think that would ideal for the long game. I think postgres is a good choice.

Do we want to have a session store? I think it wouldn't be a bad idea to include it even if its something a user can configure optionally for themselves.

**Comment by CWSpear** [comment]
Theme choice and stuff are stored in localStorage in the current version. But we could put that in Redis. Accounts also already exist via passport and GitHub logins.

**Comment by jmartin84** [comment]
yeah I think themes should be more persistent than localstorage
